### PR TITLE
Patched Quagga to allow sub-second configuration of MinLSTimer and Mi…

### PR DESCRIPTION
**Pull request by lferran**
…nLSArrival parameters

### CODE REVIEW

**Comment by oliviertilmans** [comment]
Are there any other changes than what's found in https://lists.quagga.net/pipermail/quagga-dev/2015-July/012957.html?
Could you cherry-pick that patch and apply it in order to keep author information? 

Thanks!

**Comment by lferran** [comment]
No, I just applied the patch directly from what was posted in the mailing list (copied the source in a file, and issued _git apply ospf-fast-convergence.diff_).

The final version of the patch can be found a couple of messages after, in the same thread: https://lists.quagga.net/pipermail/quagga-dev/attachments/20150727/09819c76/attachment-0001.obj

As of keeping the authorship: I am not sure how to do this. Is there any official Quagga patches repository? or should I try to look for the author's github repo?

**Comment by oliviertilmans** [comment]
You should cherry-pick that patch from the Quagga git, then apply it here. This will then preserve the authorship information + eventual commit message/signed-off-by

**Comment by lferran** [comment]
Sorry, I am a bit confused:
- I found the patch commit here: http://git.savannah.gnu.org/cgit/quagga.git/commit/?id=2ef762ed9b88e5745012c5829f8f526c95443ddf
- I am trying to copy the patch file into a local file, and then tun _git apply --check ospf-fast.patch_, but I get errors: `fatal: patch fragment without header at line 175: @@ -2024,7 +2024,7 @@ ospf_opaque_lsa_refresh_schedule (struct ospf_lsa *lsa0)`
- How am I supposed to apply the patch otherwise?

**Pull request merged**
